# Generated by Django 5.0.6 on 2024-06-14 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Albom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('sana', models.DateField(blank=True, null=True)),
                ('rasm', models.ImageField(upload_to='albomlar/')),
            ],
        ),
        migrations.CreateModel(
            name='Qoshiqchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ism', models.CharField(max_length=255)),
                ('t_sana', models.DateField(blank=True, null=True)),
                ('davlat', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Qoshiq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('janr', models.CharField(max_length=50)),
                ('davomilik', models.DurationField(blank=True, null=True)),
                ('fayl', models.FileField(blank=True, null=True, upload_to='qoshiqlar/')),
                ('albom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.albom')),
            ],
        ),
    ]
